### PR TITLE
Use `httpGet` readiness probe for proxy Pod

### PR DESCRIPTION
**Pull request by dlipovetsky**
I also noticed that the `initialDelaySeconds` values are different--does that need fixing?

### CODE REVIEW

**Comment by JoshVanL** [comment]
Working for me :)

> I also noticed that the initialDelaySeconds values are different--does that need fixing?

Probably makes sense to keep them consistent

/approve
/ok-to-test
/assign @dlipovetsky

**Comment by dlipovetsky** [comment]
Using #94 to build, and running against a dex issuer on the same machine, the proxy reports ready approximately 10 seconds after the process starts. This result is consistent.
```
$ date; ./kube-oidc-proxy --secure-port=40003 --tls-cert-file=/tmp/oidc/tls/crt.pem --tls-private-key-file=/tmp/oidc/tls/key.pem --oidc-client-id=dex-k8s-authenticator --oidc-issuer-url=https://172.17.0.3:30443/dex --oidc-username-claim=email --oidc-groups-claim=groups --oidc-ca-file=/tmp/oidc/tls/crt.pem -v=10
Sat Sep 14 12:49:17 PDT 2019
I0914 12:49:17.127312    1381 loader.go:359] Config loaded from file:  /home/daniel/.kube/kind-config-mgmt
I0914 12:49:27.144630    1381 secure_serving.go:116] Serving securely on [::]:40003
I0914 12:49:27.144717    1381 proxy.go:95] proxy ready
```

So with a 5 second initial delay, the first readiness check will fail. How about I use 15 seconds in both places?

**Comment by JoshVanL** [comment]
Yep, 15 secs seems like a reasonable time to me

**Comment by JoshVanL** [comment]
Yep, 15 secs seems like a reasonable time to me

**Pull request merged**
