### PR TITLE
Fix a couple bugs in the helm chart

### PR DESCRIPTION
**Pull request by dcherman**

### CODE REVIEW

**Comment by JoshVanL** [comment]
Cheers!
/approve
/ok-to-test
/lgtm
/release-note-none

**Comment by JoshVanL** [comment]
@dcherman CI is currently broken - waiting on https://github.com/jetstack/kube-oidc-proxy/pull/96

**Comment by JoshVanL** [comment]
Though perhaps should pass for v1.15...

**Comment by dcherman** [comment]
Seems like that was the case :)

**Pull request merged**
