### PR TITLE
Failure to provision managed worker nodes as call to kubernetes provider fails to find current kubeconfig

### PR DESCRIPTION
**Pull request by saiteja313**
terraform-aws-modules/terraform-aws-eks#690

### CODE REVIEW

**Comment by saiteja313** [comment]
@JoshVanL I signed off my commit. Can you re-review it?

**Comment by saiteja313** [comment]
@JoshVanL bump

**Comment by JoshVanL** [comment]
Hey @saiteja313, 
Sorry, missed this.

/lgtm
/approve
/ok-to-test

**Pull request merged**
