### PR TITLE
Move static manifests from demo to deploy

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>

Moves static manifests from demo to deploy since that makes more logic sense

### CODE REVIEW

**Comment by simonswine** [comment]
Needs rebase or close

/assign @JoshVanL 
/unassign

**Comment by JoshVanL** [comment]
Not sure why this is not failing
/retest

**Comment by simonswine** [comment]
Needs another rebase
/unassign
/assign @JoshVanL

**Pull request merged**
