### PR TITLE
In-cluster config only used when no client flags have been provided

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>

/assign @simonswine 

```release-notes
Adds option to configure whether to use in cluster configuration to set up connection to the backend
```

### CODE REVIEW

**Comment by simonswine** [comment]
Not too sure if keeping the current behaviour in-cluster on by default, would be preferable (assuming most people would run it that way)

wdyt @JoshVanL 

/unassign
/assign @JoshVanL

**Comment by JoshVanL** [comment]
@simonswine the reason why I set it like that was that it's not very clear that's the behaviour to new users. At least with an explicit flag + errors if neither/both are set it's clear what's going on.

**Comment by simonswine** [comment]
As discussed we should use the same behaviour core components use:

```
   if len(o.CoreAPIKubeconfigPath) > 0 {
        loadingRules := &clientcmd.ClientConfigLoadingRules{ExplicitPath: o.CoreAPIKubeconfigPath}
        loader := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, &clientcmd.ConfigOverrides{})
        kubeconfig, err = loader.ClientConfig()
        if err != nil {
            return fmt.Errorf("failed to load kubeconfig at %q: %v", o.CoreAPIKubeconfigPath, err)
        }
    } else {
        kubeconfig, err = rest.InClusterConfig()
        if err != nil {
            return err
        }
    }
```

**Comment by JoshVanL** [comment]
@simonswine Should be good now

**Pull request merged**
